import type { Metadata } from "next";
import { Comfortaa } from "@next/font/google"; // Import the Comfortaa font
import "./globals.css";
import React from "react";
import FAB from "@/components/Fab";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Load the Comfortaa font with desired options
const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights if needed
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the font class from @next/font */}
      <body className={`${comfortaa.className} antialiased`}>
        {children}
        <FAB />
      </body>
    </html>
  );
}
